* make
[[https://www.gnu.org/software/make/manual/make.pdf][GNU make Manual]]
** What is a make?
#+BEGIN_QUOTE
The make utility automatically determines which pieces of a large program need to be
 recompiled, and issues commands to recompile them. - GNU Make Manual
#+END_QUOTE
** What is a makefile?
A file that tells */make/* how to compile and link a program. It describes the relationships among files and provides commands for updating each file.
** Components of a makefile
*** target
Typically the name of a file that is generated by a program or the name of an action to be carried out.
/Example/: *clean* [Phony Target]
*Note*: /,PHONY/ targets explicitly direct make to recognize them as non-files.
*** prerequisite
A file that is used as input to create the target. (A target often depends on several files)
*** recipe
An action that */make/* carries out. May have more than one command, either on the same or own individual line.
*Note*: Must put a *<TAB>* character at the beginning of every recipe line.
*** rule
Explains how and when to remake certain files that are targets of a particular rule.
*** variables 
- Define and assign using equal (*=*)
- Retrieve the variable value through *$( )* or  *${ }*
* Examples
- makefile
#+begin_src makefile
objects = main.o kbd.o command.o display.o insert.o search.o files.o utils.o

.PHONY: clean
clean :
	rm -rf $(objects)
#+end_src
- running a makefile
#+begin_src makefile
make clean
#+end_src
